---
name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  nix-flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure the build succeeds
        run: nix build --print-build-logs

      - name: Run `nix flake check` to run formatters, linters, and tests
        run: nix flake check --print-build-logs
